### ISSUE TITLE
Documentation for upgrading from contentful.py 0.9.2?

### ISSUE THREAD

**Issue by dgirgenti** [contentful/contentful.py#30]
Hello,

In upgrading from Python 3.4 to 3.6, we are currently using contentful.py 0.9.2 which does not seem to like py3.6, and we wish to upgrade to 1.6.0 which explicitly lists py3.6 as supported.

However I've not had any luck finding lists of deprecations or breaking changes in the changelogs, and simply upgrading the library has resulted in some errors. Do you have any documentation or lists of breaking changes between these versions?

Thanks!

**Comment by dlitvakb** [comment]
Hey @dgirgenti,

This SDK, does not have a `0.x` release, we decided to start with a `1.x` release cycle to disambiguate from the deprecated unofficial SDK we previously had.

This SDK is entirely new, and as the other one was not considered official, we did not write an upgrade guide.

As for breaking changes, the whole SDK is completely different, with an extremely different API to the other one.

Therefore, I recommend taking your time to re-implement it from scratch rather than looking to do a gradual change. I know this might sound as a daunting task, but this SDK is extremely simple to use in comparison to the unofficial one.

If you have any questions on the migration, please don't hesitate to ask, I'm available through here or our [support page](https://support.contentful.com).

Hope this helps,

Cheers
